script dev2;
@rakardevanagari = [rakar-deva];
lookup cjct_devanagari_rakar_forms {
	lookupflag UseMarkFilteringSet @rakardevanagari;
	sub ka-deva rakar-deva by ka_ra-deva;
	sub kha-deva rakar-deva by kha_ra-deva;
	sub ga-deva rakar-deva by ga_ra-deva;
	sub gha-deva rakar-deva by gha_ra-deva;
	sub nga-deva rakar-deva by nga_ra-deva;
	sub ca-deva rakar-deva by ca_ra-deva;
	sub cha-deva rakar-deva by cha_ra-deva;
	sub ja-deva rakar-deva by ja_ra-deva;
	sub jha-deva rakar-deva by jha_ra-deva;
	sub nya-deva rakar-deva by nya_ra-deva;
	sub tta-deva rakar-deva by tta_ra-deva;
	sub ttha-deva rakar-deva by ttha_ra-deva;
	sub dda-deva rakar-deva by dda_ra-deva;
	sub ddha-deva rakar-deva by ddha_ra-deva;
	sub nna-deva rakar-deva by nna_ra-deva;
	sub t-deva rakar-deva by t_ra-deva;
	sub ta-deva rakar-deva by ta_ra-deva;
	sub tha-deva rakar-deva by tha_ra-deva;
	sub da-deva rakar-deva by da_ra-deva;
	sub dha-deva rakar-deva by dha_ra-deva;
	sub d-deva b-deva rakar-deva by d_b_ra-deva;
	sub na-deva rakar-deva by na_ra-deva;
	sub pa-deva rakar-deva by pa_ra-deva;
	sub pha-deva rakar-deva by pha_ra-deva;
	sub ba-deva rakar-deva by ba_ra-deva;
	sub bha-deva rakar-deva by bha_ra-deva;
	sub ma-deva rakar-deva by ma_ra-deva;
	sub ya-deva rakar-deva by ya_ra-deva;
	sub la-deva rakar-deva by la_ra-deva;
	sub lla-deva rakar-deva by lla_ra-deva;
	sub va-deva rakar-deva by va_ra-deva;
	sub sha-deva rakar-deva by sha_ra-deva;
	sub ssa-deva rakar-deva by ssa_ra-deva;
	sub sa-deva rakar-deva by sa_ra-deva;
	sub ha-deva rakar-deva by ha_ra-deva;
	sub k-deva ssa-deva rakar-deva by k_ssa_ra-deva;
	sub n-deva t-deva rakar-deva by n_t_ra-deva;
	sub s-deva t-deva rakar-deva by s_t_ra-deva;
	sub d-deva g-deva rakar-deva by d_g_ra-deva;
} cjct_devanagari_rakar_forms;
lookupflag 0;
lookup cjct_Halfdevanagari {
	sub d-deva y-deva by d_y-deva;
} cjct_Halfdevanagari;
lookup cjct_devanagari {
	sub b-deva ba-deva by b_ba-deva;
	sub b-deva va-deva by b_va-deva;
	sub c-deva ca-deva by c_ca-deva;
	sub c-deva cha-deva by c_cha-deva;
	# sub c-deva ch-deva va-deva by c_ch_va-deva;
	# sub ch-deva ya-deva by ch_ya-deva;
	# sub ch-deva va-deva by ch_va-deva;
	sub d-deva da-deva by d_da-deva;
	sub d-deva ga-deva by d_ga-deva;
	sub d-deva dha-deva by d_dha-deva;
	sub d-deva gha-deva by d_gha-deva;
	sub d-deva d-deva ya-deva by d_d_ya-deva;
	sub d-deva dh-deva ya-deva by d_dh_ya-deva;
	sub d-deva va-deva by d_va-deva;
	sub d-deva ya-deva by d_ya-deva;
	sub d-deva na-deva by d_na-deva;
	sub d-deva ba-deva by d_ba-deva;
	sub d-deva va-deva by d_va-deva;
	sub d-deva bha-deva by d_bha-deva;
	sub d-deva ma-deva by d_ma-deva;
	sub d-deva bh-deva ya-deva by d_bh_ya-deva;
	sub d-deva v-deva ya-deva by d_v_ya-deva;
	sub dd-deva dda-deva by dd_dda-deva;
	sub dd-deva ddha-deva by dd_ddha-deva;
	sub dd-deva ya-deva by dd_ya-deva;
	sub dd-deva dd-deva ya-deva by dd_dd_ya-deva;
	sub ddh-deva ddha-deva by ddh_ddha-deva;
	sub ddh-deva ya-deva by ddh_ya-deva;
	sub ddh-deva ddh-deva ya-deva by ddh_ddh_ya-deva;
	sub dh-deva va-deva by dh_va-deva;
	sub g-deva rakar-deva ya-deva by g_rakar_ya-deva;
	sub m-deva bha-deva by m_bha-deva;
	sub n-deva ca-deva by n_ca-deva;
	sub n-deva sa-deva by n_sa-deva;
	sub n-deva tta-deva by n_tta-deva;
	sub h-deva ma-deva by h_ma-deva;
	sub h-deva ya-deva by h_ya-deva;
	sub l-deva tta-deva by l_tta-deva;
	sub l-deva dda-deva by l_dda-deva;
	sub l-deva ta-deva by l_ta-deva;
	sub l-deva pa-deva by l_pa-deva;
	sub l-deva sa-deva by l_sa-deva;
	sub k-deva ta-deva by k_ta-deva;
	sub k-deva sa-deva by k_sa-deva;
	sub ph-deva sa-deva by ph_sa-deva;
	sub p-deva ja-deva by p_ja-deva;
	sub p-deva pa-deva by p_pa-deva;
	sub p-deva pha-deva by p_pha-deva;
	sub p-deva va-deva by p_va-deva;
	sub p-deva ya-deva by p_ya-deva;
	sub p-deva za-deva by p_za-deva;
	sub ph-deva ja-deva by ph_ja-deva;
	sub rr-deva ya-deva by rr_ya-deva;
	sub rr-deva ha-deva by rr_ha-deva;
	sub s-deva ja-deva by s_ja-deva;
	sub s-deva pa-deva by s_pa-deva;
	sub sh-deva va-deva by sh_va-deva;
	sub t-deva t-deva by t_t-deva;
	sub t-deva ta-deva by t_ta-deva;
	sub t-deva t-deva ta-deva by t_t_ya-deva;
	sub th-deva na-deva by th_na-deva;
	sub th-deva ya-deva by th_ya-deva;
	sub th-deva va-deva by th_va-deva;
	sub tt-deva tta-deva by tt_tta-deva;
	sub tt-deva ttha-deva by tt_ttha-deva;
	sub tt-deva ya-deva by tt_ya-deva;
	sub tth-deva ya-deva by tth_ya-deva;
	sub tt_ra-deva uuMatra-deva by tt_ra_uuMatra-deva;
	sub tt-deva tt-deva ya-deva by tt_tt_ya-deva;
	sub tta_ra-deva uuMatra-deva by tta_ra_uuMatra-deva;
	sub tth-deva tth-deva ya-deva by tth_tth_ya-deva;
	sub v-deva ya-deva by v_ya-deva;
	sub v-deva la-deva by v_la-deva;
	sub v-deva va-deva by v_va-deva;
	sub v-deva ha-deva by v_ha-deva;
} cjct_devanagari;
